apiVersion: v1
kind: Pod
metadata:
    name: my-multi-container-pod
spec:
    containers:
    - name: app
      image: busybox
      command: ['sh', '-c', "while true; do echo Hello; sleep 5; done"]
    - name: logger
      image: busybox
      command: ['sh', '-c', "while true; do echo loggin;  echo $(date) >> /var/log/hello.log ; sleep 5; done"]
      ports:
      - containerPort: 80
